# Generated by Django 5.0.7 on 2024-08-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_mod", "0002_alter_category_options_blog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="status",
            field=models.CharField(
                choices=[("Drafts", "Drafts"), ("Published", "Published")],
                default="Drafts",
                max_length=20,
            ),
        ),
    ]
